repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort (python)
      args: ["--resolve-all-configs"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: ["--config=/Users/gabriela/Projects/pycvpipeline/.flake8"]
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=/Users/gabriela/Projects/pycvpipeline/.pylintrc",
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'
    hooks:
    - id: mypy
      language: system
      types: [python]
